default: &default
  adapter: postgresql
  username: <% ENV['POSTGRES_USERNAME'] %>
  password: <% ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: event-planning-api-dev

test:
  <<: *default
  database: event-planning-api-test

production:
  <<: *default
  database: event-planning-api
